### ISSUE TITLE
SMTP Authentication Issue

### ISSUE THREAD

**Issue by chasemassey** [chasemassey/blocmarks#1]

**Comment by chasemassey** [comment]
Most recent commit has issue when sending confirmation email. Screenshot attached. Could be devise or mailgun issue. 

![screenshot from 2016-03-27 17 27 12](https://cloud.githubusercontent.com/assets/11511433/14067934/3c9c4fa6-f441-11e5-8917-d17fcdceeaf5.png)

**Comment by shannonio** [comment]
Please see commit for fix https://github.com/chasemassey/blocmarks/commit/8d1ca2bc7bcdea45f806cf6dd25540cde7d1c4b5
